spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
      file-size-threshold: 5KB
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/food_booking_app_db
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        jdbc:
          time_zone: UTC
  main:
    allow-bean-definition-overriding: true
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  data:
    web:
      pageable:
        max-page-size: 15
        page-parameter: page
        size-parameter: size
        default-page-size: 10
        one-indexed-parameters: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: error
        SQL: error
    food:
      booking:
        app: info
    net:
      sf:
        jmimemagic: error
storage.upload-directory: /var/tmp/uploads